# CMake generated Testfile for 
# Source directory: /Users/dorshay/work/tools/h3-node/h3
# Build directory: /Users/dorshay/work/tools/h3-node/h3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testH3ToGeo_test1 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r08centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test2 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r09centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test3 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r10centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test4 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r11centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test5 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r12centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test6 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r13centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test7 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r14centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test8 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r15centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test9 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r08centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test10 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r09centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test11 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r10centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test12 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r11centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test13 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r12centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test14 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r13centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test15 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r14centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test16 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r15centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test17 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r08centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test18 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r09centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test19 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r10centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test20 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r11centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test21 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r12centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test22 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r13centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test23 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r14centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test24 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r15centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test25 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res00ic.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test26 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res01ic.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test27 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res02ic.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test28 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res03ic.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testH3ToGeo_test29 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res04ic.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeo")
add_test(testGeoToH3_test30 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand05centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test31 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand06centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test32 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand07centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test33 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand08centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test34 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand09centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test35 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand10centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test36 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand11centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test37 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand12centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test38 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand13centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test39 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand14centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testGeoToH3_test40 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand15centers.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testGeoToH3")
add_test(testH3ToGeoBoundary_test41 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r08cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test42 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r09cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test43 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r10cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test44 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r11cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test45 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r12cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test46 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r13cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test47 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r14cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test48 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc05r15cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test49 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r08cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test50 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r09cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test51 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r10cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test52 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r11cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test53 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r12cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test54 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r13cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test55 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r14cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test56 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc14r15cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test57 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r08cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test58 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r09cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test59 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r10cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test60 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r11cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test61 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r12cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test62 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r13cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test63 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r14cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test64 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/bc19r15cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test65 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand05cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test66 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand06cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test67 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand07cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test68 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand08cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test69 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand09cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test70 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand10cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test71 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand11cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test72 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand12cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test73 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand13cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test74 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand14cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test75 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/rand15cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test76 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res00cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test77 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res01cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test78 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res02cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testH3ToGeoBoundary_test79 "sh" "-c" "cat /Users/dorshay/work/tools/h3-node/h3/tests/inputfiles/res03cells.txt |  /Users/dorshay/work/tools/h3-node/h3/bin/testH3ToGeoBoundary")
add_test(testCompact_test80 "/Users/dorshay/work/tools/h3-node/h3/bin/testCompact")
add_test(testKRing_test81 "/Users/dorshay/work/tools/h3-node/h3/bin/testKRing")
add_test(testHexRing_test82 "/Users/dorshay/work/tools/h3-node/h3/bin/testHexRing")
add_test(testHexRanges_test83 "/Users/dorshay/work/tools/h3-node/h3/bin/testHexRanges")
add_test(testH3ToParent_test84 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3ToParent")
add_test(testH3ToChildren_test85 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3ToChildren")
add_test(testMaxH3ToChildrenSize_test86 "/Users/dorshay/work/tools/h3-node/h3/bin/testMaxH3ToChildrenSize")
add_test(testH3Index_test87 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3Index")
add_test(testH3Api_test88 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3Api")
add_test(testH3SetToLinkedGeo_test89 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3SetToLinkedGeo")
add_test(testH3SetToVertexGraph_test90 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3SetToVertexGraph")
add_test(testLinkedGeo_test91 "/Users/dorshay/work/tools/h3-node/h3/bin/testLinkedGeo")
add_test(testPolyfill_test92 "/Users/dorshay/work/tools/h3-node/h3/bin/testPolyfill")
add_test(testVertexGraph_test93 "/Users/dorshay/work/tools/h3-node/h3/bin/testVertexGraph")
add_test(testH3UniEdge_test94 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3UniEdge")
add_test(testGeoCoord_test95 "/Users/dorshay/work/tools/h3-node/h3/bin/testGeoCoord")
add_test(testBBox_test96 "/Users/dorshay/work/tools/h3-node/h3/bin/testBBox")
add_test(testPolygon_test97 "/Users/dorshay/work/tools/h3-node/h3/bin/testPolygon")
add_test(testVec2d_test98 "/Users/dorshay/work/tools/h3-node/h3/bin/testVec2d")
add_test(testVec3d_test99 "/Users/dorshay/work/tools/h3-node/h3/bin/testVec3d")
add_test(testH3ToLocalIj_test100 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3ToLocalIj")
add_test(testH3Distance_test101 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3Distance")
add_test(testCoordIj_test102 "/Users/dorshay/work/tools/h3-node/h3/bin/testCoordIj")
add_test(testH3NeighborRotations_test103 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3NeighborRotations" "0")
add_test(testH3NeighborRotations_test104 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3NeighborRotations" "1")
add_test(testH3NeighborRotations_test105 "/Users/dorshay/work/tools/h3-node/h3/bin/testH3NeighborRotations" "2")
